export const FETCH_ACCOUNT_LIST = "FETCH_ACCOUNT_LIST";

export const DELETE_ACCOUNT = "DELETE_ACCOUNT";

export const SHOW_ACCOUNT_FORM = "SHOW_ACCOUNT_FORM";

export const CLOSE_ACCOUNT_FORM = "CLOSE_ACCOUNT_FORM";
