export const FETCH_PRODUCT_LIST = "FETCH_PRODUCT_LIST";

export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export const SHOW_PRODUCT_FORM = "SHOW_PRODUCT_FORM";

export const CLOSE_PRODUCT_FORM = "CLOSE_PRODUCT_FORM";
